classes/ValidFormBuilder/ValidForm.php, classes/ValidFormBuilder/ValidWizard.php
=> Hide elements from valuesAsHtml output if they're hidden with a condition

.travis-generate-docs.sh, .travis.yml, classes/ValidFormBuilder/Collection.php, classes/ValidFormBuilder/Element.php, classes/ValidFormBuilder/Group.php, classes/ValidFormBuilder/Select.php, classes/ValidFormBuilder/SelectGroup.php, classes/ValidFormBuilder/ValidForm.php, classes/ValidFormBuilder/ValidWizard.php
- Fixed Travis CI errors
- Added updated access token
- Improved automatic documentation generator by forcing it to only regenerate documentation when a commit is pushed to the `master` branch. This allows for working in branches without the original documentation being touched.
=> Fix Travis CI build errors and improve documentation deploy script

classes/ValidFormBuilder/ValidForm.php
If the condition is met for the first element, it automatically applies to the dynamic clones as well. Therefore we only check dynamic counter 0.
This fixes #55
=> Force dynamic counter in elementShouldDisplay method to 0

js/validform.js
=> Fixes dynamic checkbox behavior

js/validform.js
=> Implement correct selector to find clones

classes/ValidFormBuilder/ValidWizard.php
=> Index should never be less than 0

classes/ValidFormBuilder/Base.php, classes/ValidFormBuilder/Element.php
=> Adds “displaySanitize” meta key and “clear” property

classes/ValidFormBuilder/Password.php
=> Define $strOutput before using it.

classes/ValidFormBuilder/ValidForm.php
Enables extendablility of ValidForm Builder
Fixes #72
=> Make elementAsHtml methods public

classes/ValidFormBuilder/Area.php, classes/ValidFormBuilder/MultiField.php, classes/ValidFormBuilder/Navigation.php, classes/ValidFormBuilder/Password.php, classes/ValidFormBuilder/Select.php, classes/ValidFormBuilder/Text.php, classes/ValidFormBuilder/Textarea.php, classes/ValidFormBuilder/ValidForm.php, css/validform.css, js/validwizard.js
=> Apply clearfix styling directly on css definitions and remove vf__cf where used.

classes/ValidFormBuilder/Area.php, classes/ValidFormBuilder/File.php, classes/ValidFormBuilder/Group.php, classes/ValidFormBuilder/MultiField.php, classes/ValidFormBuilder/Password.php, classes/ValidFormBuilder/Select.php, classes/ValidFormBuilder/Text.php, classes/ValidFormBuilder/Textarea.php
=> Refactor toHtml methods

classes/ValidFormBuilder/Base.php
=> Implement array_unique filter for ‘class’ meta property

classes/ValidFormBuilder/Validator.php
Fix for #78. Remove the regex validation for password fields.
=> Remove regex validation for password fields

classes/ValidFormBuilder/Comparison.php, classes/ValidFormBuilder/ValidForm.php
Adds the ability to check against an array of values using a Condition.
=> Adds “in_array” Comparison for Conditions

js/validform.js, js/validwizard.js
Adds “previous” button on last wizard page and enables client side validation on last wizard page.
=> Fixes issue #105

js/validform.js
They break a lot of situations where string and numeric values are compared.
=> Fixes overaggressive strict “equal” refactors

.travis.yml
It's all in the title. Updated the integration token for notifications to Slack
=> Updated Slack integration token for TravisCI

classes/ValidFormBuilder/FieldValidator.php
=> Adds business logic for dynamic default values

classes/ValidFormBuilder/Element.php, classes/ValidFormBuilder/FieldValidator.php, classes/ValidFormBuilder/Text.php, classes/ValidFormBuilder/Textarea.php
This makes it possible to trim values before they get validated.
Closes #136.
=> feat: add pre-sanitization to the field validator

js/validform.js
Forgot about this one....
Closes #136
=> fix: add javascript logic for pre-sanitization

classes/ValidFormBuilder/Area.php, classes/ValidFormBuilder/Checkbox.php, classes/ValidFormBuilder/File.php, classes/ValidFormBuilder/Group.php, classes/ValidFormBuilder/MultiField.php, classes/ValidFormBuilder/Password.php, classes/ValidFormBuilder/Select.php, classes/ValidFormBuilder/Text.php, classes/ValidFormBuilder/Textarea.php
Enables the ability to set CSS classes on a tip element.
=> Enables tipClass parameter to actually work

classes/ValidFormBuilder/FieldValidator.php, classes/ValidFormBuilder/Password.php, classes/ValidFormBuilder/Text.php, classes/ValidFormBuilder/Textarea.php, examples/external-validation/ExternalValidation.php, examples/external-validation/external-validation.js, examples/external-validation/string-input-field-with-external-validation.php, js/validform.js
This adds an external validation, external in this context means outside validform.
The external validation can be done by your own javascript and/or php
Offers more validation possibilities
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [] Bug fix (non-breaking change which fixes an issue)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> Adds external validation.

classes/ValidFormBuilder/Base.php
Removing these methods according to the discussion in #155
=> fix(Base): remove hasFields and getFields methods from Base class, fixes #155
